apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    template: postgresql-ephemeral-template
  name: f8toggle-db
spec:
  replicas: 1
  selector:
    name: f8toggle-db
  template:
    metadata:
      labels:
        name: f8toggle-db
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: user
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_DATABASE
          value: unleashdb
        image: centos/postgresql-95-centos7@sha256:4bb406f189b9df15c3ff0e717a61d76392d41bd9d1c99fdde57c7d72cc737fca
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: f8toggle-db
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: f8toggle-db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: f8toggle-db-data

